#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

#Cores

NC='\033[0m'

BBlue='\033[1;34m'

BRed='\033[1;31m'

REGEX_ISSUE_ID="[a-za-Z0-9,\.\_\-]+-[0-9]+"

BRANCH_NAME=$(git symbolic-ref --short HEAD)

ISSUE_ID=$(echo "$BRANCH_NAME" | grep -o -E "$REGEX_ISSUE_ID")

COMMIT_MESSAGE=$(cat "$1")

if [ -z "$ISSUE_ID" ]; then

    echo -e "${Bred}Branch não está no padrão que deveria mestre... ${NC}"

    exit 1
fi

# Prevent adding a issue key in commits that already have a JIRA issue key

# i.g HEY-1: HEY-1: my feature

if [[ $COMMIT_MESSAGE == $ISSUE_ID ]]; then

    exit 0

fi

echo "$ISSUE_ID: $COMMIT_MESSAGE" >$1
